version: '3'

services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    restart: always
    command: /bin/sh -c "mkdir postgres"
    environment:
    - POSTGRES_DB=user_db
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=myrootpassword
    - PGDATA=/var/lib/postgresql/data
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    networks:
    - db_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    command: /bin/sh -c "mkdir pgadmin"
    environment:
    - PGADMIN_DEFAULT_EMAIL=root@student.42lyon.fr
    - PGADMIN_DEFAULT_PASSWORD=myrootpassword
    - PGADMIN_LISTEN_PORT=80
    ports:
    - "8080:80"
    volumes:
    - pgadmin_data:/var/lib/pgadmin
    - ./pgadmin_server.json:/pgadmin4/servers.json
    networks:
    - db_network

volumes:
  postgres_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./postgres/
  pgadmin_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./pgadmin/

networks:
  db_network:

